window.LargeMissions = [
  {
    id: "tree-planting-explorer",
    image: "assets/badges/tree-planting-explorer-card.png",
    title: "Tree Planting Explorer",
    category: "Nature",
    type: "Community Mission",
    difficulty: 3,
    duration: "2-4 hours",
    coins: 40,
    age: "6+ with help / 10+ solo",
    achievement: "Root Starter",
    summary: "Plant trees to improve biodiversity and green spaces.",
    purpose: "Plant trees to improve biodiversity and green spaces.",
    validation: "Upload a photo of the planted tree and the planting activity.",
    prep: ["shovel", "gloves", "water", "young tree or sapling"],
    steps: ["Find a tree planting event or suitable place to plant.", "Dig the planting hole.", "Plant the tree correctly.", "Water the tree after planting."]
  },
  {
    id: "car-free-explorer-day",
    image: "assets/badges/car-free-explorer-day-card.png",
    title: "Car-Free Explorer Day",
    category: "Outside",
    type: "Habit Challenge (1 day)",
    difficulty: 2,
    duration: "full day",
    coins: 35,
    age: "8+ with help / 14-18 solo depending on parents",
    achievement: "Road Replacer",
    summary: "Spend one day replacing car trips with walking, cycling, or public transport.",
    purpose: "Reduce emissions by replacing car trips with walking, cycling, or public transport.",
    validation: "Upload photos showing three trips completed without a car.",
    prep: ["bicycle, walking shoes, or public transport"],
    steps: ["Plan a day without using a car.", "Complete at least three trips without a car."]
  },
  {
    id: "neighbourhood-cleanup-investigators",
    image: "assets/badges/neighbourhood-cleanup-investigators-card.png",
    title: "Neighbourhood Cleanup Investigators",
    category: "Community",
    type: "Community Investigation Mission",
    difficulty: 3,
    duration: "2-4 hours",
    coins: 50,
    age: "8+ with help / 12+ solo",
    achievement: "Litter Clue Hunter",
    summary: "Clean a public area and investigate why litter appears there.",
    purpose: "Clean a public area and investigate why litter appears there.",
    validation: "Upload a photo of the cleaned area and a short explanation of the cause of littering.",
    prep: ["gloves", "trash bags", "phone or notebook"],
    steps: ["Clean a littered area or your favorite local park.", "Observe where trash appears most often.", "Identify the likely cause of littering.", "Do one improvement to reduce the problem."]
  },
  {
    id: "repair-cafe-apprentice",
    image: "assets/badges/repair-cafe-apprentice-card.png",
    title: "Repair Cafe Apprentice",
    category: "Learning",
    type: "Learning Mission",
    difficulty: 3,
    duration: "2-3 hours",
    coins: 30,
    age: "10+ with help / 14+ solo",
    achievement: "Workshop Learner",
    summary: "Learn repair skills and extend the life of objects.",
    purpose: "Learn repair skills and extend the life of objects.",
    validation: "Upload a photo of the item before and after repair.",
    prep: ["broken item", "repair tools or access to repair workshop"],
    steps: ["Visit a repair cafe or repair workshop.", "Work with someone experienced to repair the item.", "Complete the repair."]
  },
  {
    id: "little-animal-architect",
    image: "assets/badges/little-animal-architect-card.png",
    title: "Little Animal Architect",
    category: "Nature",
    type: "Build Mission",
    difficulty: 2,
    duration: "2-3 hours",
    coins: 25,
    age: "8+ with help / 12+ solo",
    achievement: "Habitat Builder",
    summary: "Build shelter or feeding support for small animals.",
    purpose: "Build shelter or feeding support for small animals.",
    validation: "Upload a photo of the finished structure installed outdoors.",
    prep: ["birdhouse, squirrel feeder, or insect hotel", "wood or recycled materials", "screws or glue", "basic tools"],
    steps: ["Build the shelter or feeder.", "Install it safely outdoors."]
  },
  {
    id: "wild-meadow-starter",
    image: "assets/badges/wild-meadow-starter-card.png",
    imageFit: "contain",
    imageScale: 1,
    title: "Wild Meadow Starter",
    category: "Nature",
    type: "Nature Mission",
    difficulty: 2,
    duration: "2-3 hours",
    coins: 25,
    age: "6+ with help / 10+ solo",
    achievement: "Pollinator Pathfinder",
    summary: "Create a temporary wildflower meadow for pollinators.",
    purpose: "Create a temporary wildflower meadow for pollinators.",
    validation: "Upload a photo of the land before planting and the planted meadow area.",
    prep: ["wildflower seeds", "rake or shovel", "water"],
    steps: ["Find unused land suitable for planting.", "Obtain permission if needed.", "Prepare the soil.", "Scatter wildflower seeds.", "Water the area."]
  },
  {
    id: "community-swap-day-organizer",
    image: "assets/badges/community-swap-day-organizer-card.png",
    imageFit: "contain",
    imageScale: 1,
    title: "Community Swap Day Organizer",
    category: "Community",
    type: "Community Mission",
    difficulty: 3,
    duration: "3-4 hours",
    coins: 45,
    age: "12+ with help / 16+ solo",
    achievement: "Reuse Host",
    summary: "Encourage reuse by organizing a swap event.",
    purpose: "Encourage reuse by organizing a swap event.",
    validation: "Upload a photo of the swap event.",
    prep: ["table or shared space", "items to swap", "participants"],
    steps: ["Choose a location.", "Invite participants to bring items.", "Organize items by category.", "Run the swap event."]
  },
  {
    id: "river-or-beach-guardian",
    image: "assets/badges/river-or-beach-guardian-card.png",
    title: "River or Beach Guardian",
    category: "Nature",
    type: "Nature Mission",
    difficulty: 3,
    duration: "2-3 hours",
    coins: 35,
    age: "8+ with help / 12+ solo",
    achievement: "Shore Saver",
    summary: "Remove waste from rivers, lakes, or beaches.",
    purpose: "Remove waste from rivers, lakes, or beaches.",
    validation: "Upload a photo of collected waste.",
    prep: ["gloves", "trash bags", "sun protection"],
    steps: ["Choose a river, lake, or beach area.", "Collect litter safely.", "Dispose of collected waste properly."]
  },
  {
    id: "food-rescue-helper",
    image: "assets/badges/food-rescue-helper-card.png",
    title: "Food Rescue Helper",
    category: "Community",
    type: "Community Mission",
    difficulty: 3,
    duration: "2-3 hours",
    coins: 40,
    age: "10+ with help / 14+ solo",
    achievement: "Food Flow Helper",
    summary: "Reduce food waste by helping redistribute food.",
    purpose: "Reduce food waste by helping redistribute food.",
    validation: "Upload a photo of participation in food rescue or distribution.",
    prep: ["reusable bags or containers"],
    steps: ["Join a food rescue group or food bank activity.", "Help sort or distribute food."]
  },
  {
    id: "school-sustainability-starter",
    image: "assets/badges/school-sustainability-starter-card.png",
    title: "School Sustainability Starter",
    category: "Learning",
    type: "Initiative Mission",
    difficulty: 2,
    duration: "2-3 hours planning",
    coins: 30,
    age: "12+",
    achievement: "Change Spark",
    summary: "Start a sustainability improvement in school.",
    purpose: "Start a sustainability improvement in school.",
    validation: "Upload a photo or description of the initiative.",
    prep: ["idea for improvement", "discussion with teacher or staff"],
    steps: ["Identify one sustainability improvement for school.", "Discuss it with a teacher or staff member.", "Do one improvement."]
  },
  {
    id: "planet-mission-scout",
    image: "assets/badges/planet-mission-scout-card.png",
    imageFit: "contain",
    imageScale: 1,
    title: "Planet Mission Scout",
    category: "Community",
    type: "Exploration Mission",
    difficulty: 2,
    duration: "2-3 hours",
    coins: 45,
    age: "10+ with help / 14+ solo",
    achievement: "NGO Trail Finder",
    summary: "Participate in an environmental activity organized by an NGO.",
    purpose: "Participate in an environmental activity organized by an NGO.",
    validation: "Upload a photo from the activity.",
    prep: ["find local environmental event"],
    steps: ["Find an environmental activity organized by an NGO.", "Participate in the activity."]
  },
  {
    id: "energy-provider-investigator",
    image: "assets/badges/energy-provider-investigator-card.png",
    title: "Energy Provider Investigator",
    category: "Learning",
    type: "Research Mission",
    difficulty: 3,
    duration: "1-2 hours",
    coins: 35,
    age: "12+ with help / 15+ solo",
    achievement: "Power Questioner",
    summary: "Research your home electricity provider and explore renewable options.",
    purpose: "Research your home electricity provider and explore renewable options.",
    validation: "Upload a screenshot of your current provider and a screenshot of renewable options or a message sent to the provider.",
    prep: ["electricity bill", "internet access"],
    steps: ["Identify your electricity provider.", "Research renewable energy options.", "If available, explore switching providers.", "If not available, contact the provider requesting renewable options."]
  }
];
