window.MediumMissions = [
  {
    id: "lunchbox-architect",
    title: "Lunchbox Architect",
    image: "assets/badges/lunchbox-architect-card.png",
    category: "Learning",
    type: "Medium Mission",
    difficulty: 2,
    duration: "45-60 min",
    coins: 20,
    age: "5+ with help / 8+ solo",
    achievement: "Snack Engineer",
    summary: "Design and prepare a homemade lunch using ingredients already at home.",
    purpose: "Reduce packaging waste and learn basic food preparation skills.",
    validation: "Upload a photo of the finished lunchbox.",
    prep: ["reusable lunch container", "ingredients from home", "cutting board", "knife (with help)"],
    steps: ["Look in the fridge and pantry", "Plan a simple lunch using available ingredients", "Prepare the food", "Pack it in reusable containers"]
  },
  {
    id: "plant-care-apprentice",
    title: "Plant Care Apprentice",
    image: "assets/badges/plant-care-apprentice-card.png",
    imageScale: 1.15,
    category: "Nature",
    type: "Habit Mission",
    difficulty: 2,
    duration: "7 days",
    coins: 20,
    age: "4+ with help / 7+ solo",
    achievement: "Plant Whisperer",
    summary: "Learn what a plant needs and care for it properly for a week.",
    purpose: "Understand that different plants require different care.",
    validation: "Upload a photo of the plant on day 1 and day 7.",
    prep: ["plant", "water", "notebook or phone to research plant care"],
    steps: ["Identify the plant species", "Look up its care needs", "Water or care according to those needs", "Observe how the plant changes"]
  },
  {
    id: "laundry-weather-wizard",
    title: "Laundry Weather Wizard",
    image: "assets/badges/laundry-weather-wizard-card.png",
    imageScale: 1.15,
    category: "Home Skills",
    type: "Habit Mission",
    difficulty: 2,
    duration: "7 days",
    coins: 20,
    age: "6+ with help / 9+ solo",
    achievement: "Wind Powered",
    summary: "Use air drying instead of a clothes dryer whenever possible.",
    purpose: "Save electricity and extend clothing life.",
    validation: "Upload a photo of clothes drying on a rack or line.",
    prep: ["drying rack or clothesline", "washed clothes"],
    steps: ["Wash clothes normally", "Hang them to dry", "Check if they dry faster in sun or shade"]
  },
  {
    id: "fridge-organizer",
    title: "Fridge Organizer",
    image: "assets/badges/fridge-organizer-card.png",
    category: "Home Skills",
    type: "Medium Mission",
    difficulty: 2,
    duration: "45 min",
    coins: 20,
    age: "6+ with help / 9+ solo",
    achievement: "Cold Case Solver",
    summary: "Organize one fridge shelf so food doesn’t get forgotten.",
    purpose: "Reduce food waste and make food easier to find.",
    validation: "Upload a before and after photo of the fridge shelf.",
    prep: ["cloth for cleaning", "container or tray"],
    steps: ["Remove items from one shelf", "Group similar foods together", "Place older food toward the front", "Clean the shelf"]
  },
  {
    id: "bike-explorer",
    title: "Bike Explorer",
    image: "assets/badges/bike-explorer-card.png",
    category: "Outside",
    type: "Medium Mission",
    difficulty: 2,
    duration: "45-60 min",
    coins: 25,
    age: "6+ with help / 12-16 solo depending on parents",
    achievement: "Leg Powered Traveler",
    summary: "Replace one short car trip with walking or biking.",
    purpose: "Reduce emissions and build healthy habits.",
    validation: "Upload a photo of your destination.",
    prep: ["bike or walking shoes", "helmet (if biking)"],
    steps: ["Choose a destination nearby", "Travel by bike or foot", "Notice your surroundings"]
  },
  {
    id: "recycling-sort-master",
    title: "Recycling Sort Master",
    image: "assets/badges/recycling-sort-master-card.png",
    category: "Learning",
    type: "Medium Mission",
    difficulty: 2,
    duration: "30-45 min",
    coins: 20,
    age: "6+ with help / 9+ solo",
    achievement: "Sorting Specialist",
    summary: "Sort one full bag of household recycling correctly.",
    purpose: "Learn proper recycling and avoid contamination.",
    validation: "Upload a photo of sorted recycling.",
    prep: ["recycling bag", "recycling bins"],
    steps: ["Empty the recycling bag", "Separate paper", "Separate plastic", "Separate metal", "Separate glass", "Place them in correct bins"]
  },
  {
    id: "backpack-detective",
    title: "Backpack Detective",
    image: "assets/badges/backpack-detective-card.png",
    category: "Learning",
    type: "Habit Mission",
    difficulty: 2,
    duration: "7 days",
    coins: 15,
    age: "5+ with help / 8+ solo",
    achievement: "Bag Explorer",
    summary: "Check your backpack every day to prevent forgotten food and clutter.",
    purpose: "Reduce food waste and build organization habits.",
    validation: "Upload a photo of your cleaned backpack.",
    prep: ["backpack"],
    steps: ["Empty your bag daily", "Remove wrappers and leftover food", "Repack useful items"]
  },
  {
    id: "packaging-detective",
    title: "Packaging Detective",
    image: "assets/badges/packaging-detective-card.png",
    category: "Learning",
    type: "Medium Mission",
    difficulty: 2,
    duration: "45 min",
    coins: 20,
    age: "6+ with help / 9+ solo",
    achievement: "Waste Investigator",
    summary: "Investigate packaging of household items and find better alternatives.",
    purpose: "Help families notice unnecessary packaging.",
    validation: "Upload photos of three packaged items you analyzed.",
    prep: ["household packaged items"],
    steps: ["Choose three packaged items", "Examine the packaging", "Discuss how they could be bought with less packaging"]
  },
  {
    id: "repair-apprentice",
    title: "Repair Apprentice",
    image: "assets/badges/repair-apprentice-card.png",
    category: "Learning",
    type: "Medium Mission",
    difficulty: 2,
    duration: "60-90 min",
    coins: 25,
    age: "7+ with help / 10+ solo",
    achievement: "Fix-It Apprentice",
    summary: "Learn how to repair one everyday object.",
    purpose: "Encourage repair instead of replacement.",
    validation: "Upload before and after photos.",
    prep: ["item to repair", "simple tools"],
    steps: ["Identify the problem", "Learn how to fix it", "Attempt the repair"]
  },
  {
    id: "garden-helper",
    title: "Garden Helper",
    image: "assets/badges/garden-helper-card.png",
    category: "Nature",
    type: "Medium Mission",
    difficulty: 2,
    duration: "60-90 min",
    coins: 25,
    age: "5+ with help / 8+ solo",
    achievement: "Garden Guardian",
    summary: "Help care for a garden or outdoor plants.",
    purpose: "Connect with nature and understand plant care.",
    validation: "Upload a photo of the gardening work.",
    prep: ["watering can", "gloves", "small tools"],
    steps: ["Water plants", "Remove weeds", "Clean the area"]
  },
  {
    id: "neighborhood-pathfinder",
    title: "Neighborhood Pathfinder",
    image: "assets/badges/neighborhood-pathfinder-card.png",
    category: "Outside",
    type: "Medium Mission",
    difficulty: 2,
    duration: "45-60 min",
    coins: 20,
    age: "6+ with help / 9+ solo",
    achievement: "Local Explorer",
    summary: "Explore your neighborhood and identify useful community places.",
    purpose: "Help kids learn about their local community.",
    validation: "Upload a photo of one place you discovered.",
    prep: ["walking shoes"],
    steps: ["Walk around your area", "Find helpful places (park, library, shop)"]
  },
  {
    id: "family-energy-audit",
    title: "Family Energy Audit",
    image: "assets/badges/family-energy-audit-card.png",
    imageScale: 1.04,
    imagePosition: "center top",
    category: "Home Skills",
    type: "Medium Mission",
    difficulty: 2,
    duration: "60 min",
    coins: 25,
    age: "7+ with help / 10+ solo",
    achievement: "Energy Investigator",
    summary: "Inspect your home and identify energy waste.",
    purpose: "Help families notice how energy is used at home.",
    validation: "Upload photos of three improvements made.",
    prep: ["notebook", "access to household devices"],
    steps: ["Walk through the house", "Identify unnecessary energy use", "Suggest improvements"]
  }
];
