window.SmallMissions = [
  {
    id: "button-wizard",
    title: "Button Wizard",
    image: "assets/badges/button-wizard-card.png",
    category: "Learning",
    type: "Quick Mission",
    difficulty: 1,
    duration: "15-20 min",
    coins: 10,
    age: "4+ with help / 7+ solo",
    achievement: "Thread Apprentice",
    badge: "needle-thread",
    summary: "Sew a loose or missing button back onto clothing.",
    purpose: "Repair clothing instead of replacing it.",
    validation: "Upload a before and after photo.",
    prep: ["needle", "thread", "button"],
    steps: [
      "Find a loose or missing button",
      "Sew the button securely",
      "Test that it holds"
    ]
  },
  {
    id: "lights-ninja",
    title: "Lights Ninja",
    image: "assets/badges/lights-ninja-card.png",
    category: "Learning",
    type: "Habit Mission",
    difficulty: 1,
    duration: "7 days",
    coins: 10,
    age: "4+",
    achievement: "Light Ninja",
    badge: "light-switch",
    summary: "Turn off lights when leaving rooms.",
    purpose: "Save electricity and build energy awareness.",
    validation: "Self-check for 7 days and send an email confirmation.",
    prep: [],
    steps: [
      "Turn off lights when leaving a room",
      "Do a quick evening light check",
      "Repeat for 7 days"
    ]
  },
  {
    id: "toy-hospital",
    title: "Toy Hospital",
    image: "assets/badges/toy-hospital-card.png",
    category: "Home",
    type: "Quick Mission",
    difficulty: 1,
    duration: "15-20 min",
    coins: 10,
    age: "3+ with parent",
    achievement: "Toy Doctor",
    badge: "toy-repair",
    summary: "Repair a broken toy instead of throwing it away.",
    purpose: "Teach repair instead of replacement.",
    validation: "Upload before and after photo.",
    prep: ["tape or glue"],
    steps: [
      "Find a broken toy",
      "Repair it together",
      "Test it again"
    ]
  },
  {
    id: "sock-detective",
    title: "Sock Detective",
    image: "assets/badges/sock-detective-card.png",
    category: "Home",
    type: "Quick Mission",
    difficulty: 1,
    duration: "10-15 min",
    coins: 7,
    age: "3+",
    achievement: "Laundry Detective",
    badge: "sock-detective",
    summary: "Find and match lonely socks after laundry.",
    purpose: "Avoid buying new socks unnecessarily.",
    validation: "Photo of matched pairs.",
    prep: ["laundry basket"],
    steps: [
      "Gather unmatched socks",
      "Match pairs",
      "Put them back in drawer"
    ]
  },
  {
    id: "fridge-detective",
    title: "Fridge Detective",
    image: "assets/badges/fridge-detective-card.png",
    category: "Home",
    type: "Quick Mission",
    difficulty: 1,
    duration: "10 min",
    coins: 7,
    age: "4+",
    achievement: "Fridge Explorer",
    badge: "fridge-detective",
    summary: "Find foods that should be eaten soon.",
    purpose: "Reduce food waste.",
    validation: "Photo of the items.",
    prep: ["open fridge"],
    steps: [
      "Check the fridge",
      "Choose 3 foods that will go bad soon",
      "Move them to the front to use them first"
    ]
  },
  {
    id: "speedy-shower",
    title: "Speedy Shower",
    image: "assets/badges/speedy-shower-card.png",
    category: "Home",
    type: "Habit Mission",
    difficulty: 1,
    duration: "5 days",
    coins: 8,
    age: "5+",
    achievement: "Quick Shower Hero",
    badge: "speedy-shower",
    summary: "Take showers under five minutes.",
    purpose: "Save water and heating energy.",
    validation: "Send a photo of the timer or self-check for 5 days and send an email confirmation.",
    prep: ["timer"],
    steps: [
      "Start timer",
      "Finish shower under 5 minutes",
      "Repeat for 5 days"
    ]
  },
  {
    id: "mini-cleanup",
    title: "Mini Park Cleanup",
    image: "assets/badges/mini-cleanup-card.png",
    category: "Outside",
    type: "Quick Mission",
    difficulty: 1,
    duration: "15-20 min",
    coins: 10,
    age: "4+ with adult",
    achievement: "Neighborhood Helper",
    badge: "cleanup",
    summary: "Pick up at least 10 pieces of litter.",
    purpose: "Cleaner shared spaces.",
    validation: "Photo of collected litter.",
    prep: ["gloves", "trash bag"],
    steps: [
      "Choose small outdoor area",
      "Collect 10 pieces of litter",
      "Dispose properly"
    ]
  },
  {
    id: "plant-guardian",
    title: "Little Plant Guardian",
    image: "assets/badges/plant-guardian-card.png",
    category: "Outside",
    type: "Quick Mission",
    difficulty: 1,
    duration: "15 min",
    coins: 10,
    age: "3+",
    achievement: "Little Gardener",
    badge: "plant",
    summary: "Plant seeds or a small plant.",
    purpose: "Encourage greenery and care for living things.",
    validation: "Photo of planted pot.",
    prep: ["pot", "soil", "seeds"],
    steps: [
      "Prepare soil",
      "Plant seeds",
      "Water the planted seeds"
    ]
  },
  {
    id: "donation-adventure",
    title: "Donation Adventure",
    image: "assets/badges/donation-adventure-card.png",
    category: "Giving",
    type: "Quick Mission",
    difficulty: 2,
    duration: "30-45 min",
    coins: 15,
    age: "3+ with parents",
    achievement: "Generous Heart",
    badge: "donation",
    summary: "Donate five usable items.",
    purpose: "Help others and extend item life.",
    validation: "Photo at donation location.",
    prep: ["donation bag"],
    steps: [
      "Choose five usable items",
      "Pack them",
      "Take them to donation center or donate them directly to a person in need"
    ]
  },
  {
    id: "book-traveler",
    title: "Book Traveler",
    image: "assets/badges/book-traveler-card.png",
    category: "Giving",
    type: "Quick Mission",
    difficulty: 1,
    duration: "10 min",
    coins: 7,
    age: "4+",
    achievement: "Story Sharer",
    badge: "book-traveler",
    summary: "Pass a finished book to someone else.",
    purpose: "Encourage reading and sharing.",
    validation: "Photo of book exchange.",
    prep: ["book"],
    steps: [
      "Choose a finished book",
      "Give it to someone else"
    ]
  },
  {
    id: "leftover-champion",
    title: "Leftover Champion",
    image: "assets/badges/leftover-champion-card.png",
    category: "Home",
    type: "Habit Mission",
    difficulty: 1,
    duration: "3 days",
    coins: 7,
    age: "4+",
    achievement: "Food Saver",
    badge: "leftover",
    summary: "Eat leftovers before cooking new food.",
    purpose: "Reduce food waste.",
    validation: "Photo of leftover meal.",
    prep: ["leftovers"],
    steps: [
      "Check fridge",
      "Eat leftovers first",
      "Repeat for 3 days"
    ]
  },
  {
    id: "standby-scout",
    title: "Standby Scout",
    image: "assets/badges/standby-scout-card.png",
    category: "Learning",
    type: "Quick Mission",
    difficulty: 1,
    duration: "10 min",
    coins: 8,
    age: "6+",
    achievement: "Energy Scout",
    badge: "standby",
    summary: "Find devices on standby and turn them off.",
    purpose: "Reduce electricity waste.",
    validation: "Photos of devices switched off.",
    prep: ["walk around house"],
    steps: [
      "Find devices with standby lights",
      "Ask parent if safe to turn off",
      "Turn off approved devices"
    ]
  }
];
